const FETCH_LIST = 'FETCH_LIST';
const FETCH_TOP_LIST = 'FETCH_TOP_LIST';
const FETCH_CART = 'FETCH_CART';
const FETCH_LANGUAGE = 'FETCH_LANGUAGE'
const PUT_LOADING = 'PUT_LOADING';
const PUT_CART = 'PUT_CART';
const PUT_LOGIN = 'PUT_LOGIN'
const PUT_LOGOUT = 'PUT_LOGOUT'
const PUT_LANGUAGE = 'PUT_LANGUAGE'

export const actionTypes = {
  FETCH_LIST,
  FETCH_TOP_LIST,
  FETCH_CART,
  FETCH_LANGUAGE,
  PUT_CART,
  PUT_LOGIN,
  PUT_LOGOUT,
  PUT_LOADING,
  PUT_LANGUAGE
};
