const FETCH_LIST = 'FETCH_LIST';
const FETCH_TOP_LIST = 'FETCH_TOP_LIST';
const FETCH_CART = 'FETCH_CART';
const PUT_CART = 'PUT_CART';
const PUT_LOGIN = 'PUT_LOGIN'
const PUT_LOGOUT = 'PUT_LOGOUT'

export const actionTypes = {
  FETCH_LIST,
  FETCH_TOP_LIST,
  FETCH_CART,
  PUT_CART,
  PUT_LOGIN,
  PUT_LOGOUT,
};
